### ISSUE TITLE
재설치

### ISSUE THREAD

**Issue by lisabeth107** [dlimpid/nims-academy-2019-02#3]
재설치하고 jupyter lab을 실행하면 (Run을 누르지 않고) 다음과 같은 화면이 나옵니다.

![first](https://user-images.githubusercontent.com/47913535/53287451-946d8f00-37bf-11e9-92d1-6b77e33efbe3.JPG)

![error_starting_kernel](https://user-images.githubusercontent.com/47913535/53287423-40fb4100-37bf-11e9-888c-5001ac8fc294.JPG)

하지만 결과는 제대로 나옵니다.

![1](https://user-images.githubusercontent.com/47913535/53287380-b0bcfc00-37be-11e9-954c-25c27c6a414e.JPG)

그런데 kernel에 오류가 있습니다.
![kernel error](https://user-images.githubusercontent.com/47913535/53287394-ecf05c80-37be-11e9-82c5-ebe1b66032dc.JPG)
![no kernel](https://user-images.githubusercontent.com/47913535/53287395-ed88f300-37be-11e9-8aaa-362e7bab9c2b.JPG)

Run all cells을 누르면 나왔던 결과들이 모두 사라지고 아무것도 뜨지 않습니다.
![error](https://user-images.githubusercontent.com/47913535/53287429-5a03f200-37bf-11e9-8026-63962329377a.JPG)

문제가 있는 것인가요?

혹시 몰라 error_starting_kernel 코드를 첨부합니다.

```
Traceback (most recent call last):
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\lisab\Anaconda3\envs\nims-academy\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
```

prompt 코드는 txt파일로 첨부합니다.

[error.txt](https://github.com/dlimpid/nims-academy-2019-02/files/2896873/error.txt)

**Comment by dlimpid** [comment]
nims-academy를 activate한 상태에서 `jupyter kernelspec list`라고 치시면 디렉토리 위치가 출력되는데 (아마 C:\\Users\lisab\Anaconda3\envs\nims-academy\share\jupyter\kernels\python3) 그 곳으로 가셔서 kernel.json을 Atom이나 메모장으로 열어 보시면 3줄에 어떻게 나오나요? 만약 `C:\\Users\\lisab\\Anaconda3\\python.exe`이나 `C:\\Users\\lisab\\Miniconda3\\python.exe`이라고 되어 있다면 `C:\\Users\\lisab\\Anaconda3\\envs\\nims-academy\\python.exe`이라고 바꿔 보세요.

**Comment by lisabeth107** [comment]
드디어 됐습니다.

늦은 시간까지 신경쓰시게 해서 죄송하고 정말 고맙습니다.

**Comment by dlimpid** [comment]
해결 되셨다니 다행입니다. 아카데미 장소에서 뵙겠습니다. 😄
